# Tareas:
### Crear tarea para usuario 3 (ver URL)
POST http://localhost:3000/api/v1/user/3/tareas
Content-Type: application/json

{
    "tarea": "Hacer un front",
    "isCompletada": false
}

### Obtener todas las tareas
GET http://localhost:3000/api/v1/user/1/tareas

### Obtener tarea
GET http://localhost:3000/api/v1/user/3/tareas/4

### Editar tarea
PUT http://localhost:3000/api/v1/user/1/tareas/3
Content-Type: application/json

{
    "tarea": "Nueva tarea",
    "isCompletada": "False",
}

### Eliminar tarea
DELETE http://localhost:3000/api/v1/user/1/tareas/3